import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "./FilterSelection.scss";
import { faTimes } from "@fortawesome/free-solid-svg-icons";
import { ChangeEvent, useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { hideSearchFilter } from "../../store/slices/app-slice";

const dataList = {
  raga: [
    "Aanaka Dhundhubi",
    "Aandi Vannam",
    "Aasa Manjari",
    "Abhayam",
    "Abheri",
    "Abherini",
    "Abhimanini",
    "Abhiramam",
    "Abhiru",
    "Abhogi",
    "Abra Kethi",
    "Abradesi",
    "Achala Natta",
    "Adan",
    "Adbhoda",
    "Adhipathi",
    "Adi Bhairavi",
    "Adi Panchamam",
    "Adidesya",
    "Adivarali",
    "Adivasu",
    "Agama Priya",
    "Aghora Priya",
    "Agnidhara",
    "Agnikopam",
    "Ahiri Nata",
    "Ahiri",
    "Ahori",
    "Aimukham",
    "Airavathi",
    "Alakavali",
    "Alankara Priya",
    "Alankaran",
    "Alankari",
    "Alapi",
    "Alarmagal",
    "Alaru",
    "Alivardhana",
    "Alla Gaathri",
    "Amapanchamam",
    "Amarasena Priya",
    "Amaravali",
    "Amaravathi",
    "Amari",
    "Amba Manohari (Vasantha Sri)",
    "Ambalika",
    "Ambhojini",
    "Ambika",
    "Ambikai Priyan",
    "Amboruha",
    "Amra Panchamam",
    "Amrith Behag",
    "Amritha Dhanyasi",
    "Amritha Gowri",
    "Amritha Panchamam",
    "Amritha Rakshani",
    "Amritha Swarupini",
    "Amrithalahari",
    "Amrithavarshini",
    "Amruta Vasantham",
    "Amrutha Lakshmi",
    "Amrutha Tarangini",
    "Amrutha Vahini",
    "Amrutharanjani",
    "Amsumali",
    "Amudha Valli",
    "Anagan",
    "Anamayan",
    "Ananda Bhairavi",
    "Ananda Bhogi",
    "Ananda Guhan",
    "Ananda Lahari",
    "Ananda Leela",
    "Ananda Mukhi",
    "Ananda Rupa",
    "Ananda Varidhi",
    "Anandanatani",
    "Anandavalli",
    "Anandh Kalyani",
    "Anandhan",
    "Anandhi",
    "Anangadhari",
    "Ananta",
    "Andhali Kurinji",
    "Andhali",
    "Andhari",
    "Andholika",
    "Andhra Desika",
    "Angalatha",
    "Angayarkanni",
    "Anguru",
    "Anikini",
    "Anilamadhya",
    "Anilavali",
    "Anjanaadri",
    "Anjanavati",
    "Anna Panchamam",
    "Annal",
    "Annavaridhi",
    "Antharavahini",
    "Anukanti",
    "Aparupam",
    "Aprameya",
    "Arabhi",
    "Aramba Desi",
    "Arani",
    "Ardha Desika",
    "Ardhrambari",
    "Arga Vardhani",
    "Arga Yoga",
    "Aruna Chandrika",
    "Aruna Kantha",
    "Arunagiri",
    "Arunajwalitha",
    "Arunakriya",
    "Arunambari",
    "Arunan",
    "Arunangi",
    "Aruran",
    "Aryamathi",
    "Asampada",
    "Asangadhari",
    "Asathi",
    "Asaveri (Kanaka Saveri)",
    "Asaveri Thodi",
    "Ashta Murthi",
    "Ashta Vadam",
    "Ashtapada",
    "Ashti",
    "Asritha Ranjani",
    "Atana",
    "Atthan",
    "Avaari",
    "Avikarai",
    "Avivardana",
    "Ayan",
    "Azaladi",
    "B",
    "Baava Bharanam",
    "Badakarani",
    "Badari Vasantham",
    "Badra Vazhai",
    "Badra",
    "Badragandhari",
    "Badrakara",
    "Badrasarangaleela",
    "Badri",
    "Badrika",
    "Bagavat Priya",
    "Bahali",
    "Bahudhamini",
    "Bahudhari Bahvdaya",
    "Bahumarini",
    "Bahurupi",
    "Bairagi Bairav",
    "Bairava Dhwani",
    "Bairavam",
    "Bala Bheethi",
    "Bala Charithra",
    "Bala Manjari",
    "Bala Sadasa",
    "Balabhee",
    "Balachandra",
    "Baladhayaki",
    "Balagambeerya",
    "Balavam",
    "Balika Vasantham",
    "Balipalam",
    "Bammani",
    "Bana Vasantham",
    "Bandhu",
    "Bangala Gowla",
    "Bangala",
    "Bangara Priya",
    "Barbara",
    "Barga Priya",
    "Barmambari",
    "Barmangi",
    "Baroda",
    "Basamana",
    "Baulangi",
    "Bauli",
    "Bava Bharanam",
    "Bava Hamsa",
    "Bava Manohari",
    "Bavasindhu",
    "Begada Sarang",
    "Begada",
    "Behag",
    "Bhadra Sri",
    "Bhadra Todi",
    "Bhadra Vahini",
    "Bhadra Vibhasitha",
    "Bhagae Sri Kannada",
    "Bhagae Sri",
    "Bhagamanjari",
    "Bhagavatha Ranjana",
    "Bhagavathi",
    "Bhagesri Bahar",
    "Bhagirathi",
    "Bhagya Ranjani",
    "Bhagya Sabari",
    "Bhairav",
    "Bhairavi",
    "Bhaktapriya",
    "Bhala Chandrika",
    "Bhala Goshi",
    "Bhala Nandini",
    "Bhalahamsa",
    "Bhallathi",
    "Bhama Gaula",
    "Bhamamani",
    "Bhanu Chandrika",
    "Bhanu Chudamani",
    "Bhanu Deepakam",
    "Bhanu Deeparam",
    "Bhanu Dhanyasi",
    "Bhanu Gandhi",
    "Bhanu Gaula",
    "Bhanu Jyotishmati",
    "Bhanu Keervani",
    "Bhanu Kokila",
    "Bhanu Manjari",
    "Bhanu Prathpam",
    "Bhanudeepam",
    "Bhanukirani",
    "Bhanukriya",
    "Bhanumathi",
    "Bhanupriya",
    "Bhanutha",
    "Bharat",
    "Bharathi",
    "Bhargavi",
    "Bharma Kesari",
    "Bharvidhwaja",
    "Bhashini",
    "Bhashsmruthi",
    "Bhaskara Priya",
    "Bhaskaran",
    "Bhauman",
    "Bhaumukhi (Bhanumukhi)",
    "Bhava Kesari",
    "Bhavajapriya",
    "Bhavali",
    "Bhavani",
    "Bhavayanai",
    "Bhavukadhayini",
    "Bhavya Leela",
    "Bherikarnika",
    "Bhikara Goshini",
    "Bhilavali",
    "Bhimplas",
    "Bhindu Herali",
    "Bhindu Kalanga",
    "Bhindu Kalinga",
    "Bhinna Herali (Bhinna Paurali)",
    "Bhinna Kaisiki",
    "Bhinna Nishadam",
    "Bhinna Panchamam",
    "Bhinna Shadjam",
    "Bhinna Varali",
    "Bhishmavali",
    "Bhoga Chaya Nattai",
    "Bhoga Chintamani",
    "Bhoga Devakriya",
    "Bhoga Dhanyasi",
    "Bhoga Dhwaja",
    "Bhoga Dwaji",
    "Bhoga Leela",
    "Bhoga Ranjani",
    "Bhoga Rasali",
    "Bhoga Samantham",
    "Bhoga Saveri",
    "Bhoga Sikamani",
    "Bhoga Sindhu",
    "Bhoga Vardhani",
    "Bhoga Vasantham",
    "Bhogavarali",
    "Bhogavathi",
    "Bhogeswari",
    "Bhogi Bhairavi",
    "Bhogi",
    "Bhogini",
    "Bhoo Ranjani",
    "Bhoop",
    "Bhoopala Chintamani",
    "Bhoopala Manohari",
    "Bhoopala Tarangini",
    "Bhoopalam",
    "Bhoopalika",
    "Bhosala",
    "Bhramara Hamsi",
    "Bhramara Kokila",
    "Bhramara Kusumam",
    "Bhramara Puttari",
    "Bhramara Saranga",
    "Bhramara Suki",
    "Bhramara Vardhani",
    "Bhudesa Priya",
    "Bhudha Manohari",
    "Bhudha Mayuram",
    "Bhudha Ranjani",
    "Bhudhan",
    "Bhujagamani",
    "Bhujagesvari",
    "Bhujanga Chintamani",
    "Bhujangi",
    "Bhujangini",
    "Bhukti Priya (Yaksha Priya)",
    "Bhupala Panchamam",
    "Bhupala Ranjani",
    "Bhusha Kalyani",
    "Bhushana Dharini",
    "Bhushani",
    "Bhushavali",
    "Bhuthanathan",
    "Bhuvana Gandhari",
    "Bhuvana Kuntala",
    "Bhuvana Ranjani",
    "Bhuvana Sundara",
    "Bhuvanamohini",
    "Bhuvaneswari",
    "Bhuyo Mani",
    "Bibasu",
    "Bidajapriya",
    "Bidal",
    "Bilahari",
    "Bilaval",
    "Binavikriarn",
    "Binna Gandhari",
    "Biyandai Gandharam (Navroj)",
    "Boap Kalyan",
    "Bowli Vasantham",
    "Brahma Leela",
    "Brahmi",
    "Bramara Bhogi",
    "Bramara Dwani",
    "Bramara Kethana",
    "Bramara Narayani",
    "Bramara Tarangini",
    "Bramara Uttari",
    "Bramara Vardhini",
    "Bramara",
    "Bramarambika Manjari",
    "Brindavana Desakshi",
    "Brindavana Kannada",
    "Brindavana Salagam",
    "Brindavana Saranga",
    "Brindavani Sarang (Madyamavathi)",
    "Brindavani",
    "Bringa Dwani",
    "Bringa Kuraga",
    "Bringi",
    "Brungamohi",
    "Brungi Vilasitha",
    "Bruravi",
    "Brurayasi",
    "Bruthulika",
    "Buddha Vahini",
    "Buddhan",
    "Byag",
    "C",
    "Chaitaka Ranjani",
    "Chakantha",
    "Chakari",
    "Chakkara Kuliya",
    "Chakora Dhwani",
    "Chakra Dhari",
    "Chakra Manjari",
    "Chakra Pradiptam",
    "Chakra",
    "Chakrodhari",
    "Chala Kesari",
    "Chalana Varali",
    "Chalana",
    "Chalani",
    "Chamara Kriya",
    "Chamaram",
    "Champa Herali",
    "Champak",
    "Champaka Latha",
    "Champaka Malika",
    "Champaka Vidhari",
    "Champakamali",
    "Champalatha",
    "Champolini",
    "Chamundi",
    "Chandhanachalam",
    "Chandhanagandhi",
    "Chandika",
    "Chandra (Kadaram)",
    "Chandra Desika",
    "Chandra Gandharam",
    "Chandra Hasitha",
    "Chandra Jyothi",
    "Chandra Kala",
    "Chandra Kantham",
    "Chandra Kauns",
    "Chandra Kausika",
    "Chandra Kirani",
    "Chandra Mandana",
    "Chandra Prabha",
    "Chandra Priya",
    "Chandra Rekha",
    "Chandra Sri",
    "Chandra Swarupi",
    "Chandra Vadana",
    "Chandrachooda",
    "Chandrachuda Priya",
    "Chandradhari",
    "Chandrasekara Priya",
    "Chandrika (Purna Chandrika)",
    "Chandrika Dawali",
    "Chandrika Gowla",
    "Chandrika Thodi",
    "Chandrikya",
    "Chandrodhari",
    "Chankarantakam",
    "Chapa Gantarava (Chapaganta)",
    "Chara Chandini",
    "Chara Vibhashini",
    "Chara Vibhasitha",
    "Charavali",
    "Charavathi",
    "Charu Kunthala",
    "Charuvardhani",
    "Chathuramba",
    "Chathuranana Priya",
    "Chathurangini",
    "Chatradhari",
    "Chaturanana",
    "Chaya Bauli",
    "Chaya Kambhoji",
    "Chaya Kausika",
    "Chaya Malavi",
    "Chaya Maruva",
    "Chaya Nattai",
    "Chaya Ranjani",
    "Chaya Rudra",
    "Chaya Saindhavi",
    "Chaya Sankarabaranam",
    "Chaya Sindhu",
    "Chaya Sopitha",
    "Chaya Tarangini",
    "Chaya Vardhini",
    "Chaya",
    "Chayagowla",
    "Chayagowri",
    "Chayanarayani",
    "Chayavathi",
    "Chayavela",
    "Cheekamaram",
    "Chekarinika",
    "Chenchudhatani",
    "Chenchukamboji",
    "Chendhuruthi (Madyamavathi)",
    "Chengalvarayan",
    "Chera Kurinji",
    "Chetagauri",
    "Chethulavali",
    "Chevvalli",
    "Chidambujavathi",
    "Chinmayee",
    "Chintaramani (Singaramani)",
    "Chinthamani",
    "Chirandi",
    "Chitanandi",
    "Chitra Chandrika",
    "Chitra Malika",
    "Chitra Mandira",
    "Chitra Saura",
    "Chitra Vaditha",
    "Chitra Vani",
    "Chitra Varali",
    "Chitramani",
    "Chitrarupi",
    "Chitrini",
    "Chitswarupi (Chitraswarupi)",
    "Chitta Dhyuthi",
    "Chitta Modhini",
    "Chitta Mohini",
    "Chitta Ranjani",
    "Chitta Sena",
    "Chittha Ranjillini",
    "Chitthakarshini",
    "Chodha Ranjani",
    "Chola Kurinji",
    "Chouri Sena",
    "Chowka Bheeru",
    "Chudamani",
    "Churnika Vinodhini",
    "Chutavali",
    "D",
    "Daana Ranjani",
    "Dadha Kunda",
    "Daivata Chandrika",
    "Daka",
    "Dakka",
    "Damaruga Priya",
    "Damayanthi",
    "Damba Kousika",
    "Dankamani",
    "Danvi (Davvi)",
    "Darardhari",
    "Dasa Nandini",
    "Daumya",
    "Daureyani",
    "Dauri",
    "Daya Ranjani",
    "Dayasyani",
    "Deekshanarathi",
    "Deekshangi",
    "Deena Dhyuthi",
    "Deenar Neya",
    "Deepa Kanthi",
    "Deeparam",
    "Deepika Vasantham",
    "Deepika",
    "Deerga Nandini",
    "Deerga Tarangini",
    "Desa Gaula",
    "Desa Kalyani",
    "Desa Mukhari",
    "Desa Ranjani",
    "Desa Sri",
    "Desa",
    "Desakya",
    "Desamani",
    "Deshyandhali",
    "Desi (Desh)",
    "Desi Natakurinji",
    "Desi Simharam",
    "Desika Bangala",
    "Desika Rudri",
    "Desiya Bangala",
    "Desiya Thodi",
    "Desya Begada",
    "Desya Ganavaridhi",
    "Desya Gaula",
    "Desya Kannada",
    "Desya Kapi",
    "Desya Manohari",
    "Desya Maruva",
    "Desya Mukhari",
    "Desya Natakurinji",
    "Desya Regupti",
    "Desya Revagupti",
    "Desya Vali",
    "Desyagowri (Desikagowri)",
    "Desyanarayani",
    "Desyasurati",
    "Deva Gandharam",
    "Deva Gandhari",
    "Deva Hamsika",
    "Deva Kamala Narayani",
    "Deva Kantha",
    "Deva Keervani",
    "Deva Kurinji",
    "Deva Kusumavali",
    "Deva Malavi",
    "Deva Manohari",
    "Deva Sabhai",
    "Deva Salakam",
    "Devakeernava (Dhruvakeernava)",
    "Devakoti",
    "Devakunjari",
    "Devamalaka",
    "Devamani",
    "Devamritha Vahini",
    "Devamruthavarshani",
    "Devamukhi",
    "Devaranji",
    "Devasraya",
    "Devi",
    "Dhadhyomathi",
    "Dhairya Mukhi",
    "Dhairyodhari",
    "Dhakshayani",
    "Dhakshinamurthi",
    "Dhali Varali",
    "Dhamalaki",
    "Dhamavathi",
    "Dhamboli",
    "Dhana Kapi",
    "Dhana Kriyadhathu",
    "Dhana Manjari",
    "Dhana Rakshasa",
    "Dhana Ranjani",
    "Dhanapalini",
    "Dhanasri",
    "Dhandapani",
    "Dhandayana",
    "Dhanta Panchamam",
    "Dhanta Vasantha",
    "Dhanu Pratapa",
    "Dhanu Priya",
    "Dhanukari",
    "Dhanyasi",
    "Dhara Pallavam",
    "Dharani Manohari",
    "Dharbakoleela",
    "Dharbari Kanada",
    "Dharbha Koola",
    "Dharbha Manjari",
    "Dharma Kottani",
    "Dharma Prakasini",
    "Dharma Ranjani",
    "Dharmalaki",
    "Dharmini",
    "Dharshika",
    "Dhasu Mukhi",
    "Dhathu Priya",
    "Dhatru Manohari",
    "Dhatthiri",
    "Dhatu Manjari",
    "Dhaujanka",
    "Dhaulika",
    "Dhautha Panchamam",
    "Dhavala Kesari",
    "Dhavala Sarasiruha",
    "Dhavala Vahini",
    "Dhavala Varali",
    "Dhavalangam",
    "Dhavalangi",
    "Dhavali Hamsi",
    "Dhavalika Gaula",
    "Dhavalika Leela",
    "Dhayalan",
    "Dhayavati",
    "Dheena Vasantha",
    "Dheepa Kriya",
    "Dheepakam",
    "Dheepika Vijayam",
    "Dheera Kunthali",
    "Dheera Saveri",
    "Dheera Swarupini",
    "Dheera Varali",
    "Dheerakari",
    "Dheeramathi",
    "Dheerankari",
    "Dheerga Dharsini",
    "Dheerga Mangali",
    "Dheergika",
    "Dheerkala",
    "Dheevika Mandini",
    "Dhehiali",
    "Dhesakshi",
    "Dhesya Kamas",
    "Dheva Bharana",
    "Dheva Gandhari",
    "Dheva Ghosha Priya",
    "Dheva Giri",
    "Dheva Gupta",
    "Dheva Kriya",
    "Dheva Mukhari",
    "Dheva Nayaki",
    "Dheva Ranjani",
    "Dheva Rashtra",
    "Dheva Saveri",
    "Dheva Sena",
    "Dhinakaran",
    "Dhivya Gandhari",
    "Dhivya Ganthi",
    "Dhivya Panchamam",
    "Dhivya Samanthini",
    "Dhivyam Dorini",
    "Dhivyamavathi",
    "Dhivyambari",
    "Dhoka",
    "Dhombi",
    "Dhorali",
    "Dhosha Rahitha Swarupi",
    "Dhoumya",
    "Dhowlika",
    "Dhowmya Raga",
    "Dhowtha Panchamam",
    "Dhruta Vardana",
    "Dhrutha Rupa",
    "Dhruthi",
    "Dhundhuma Priya",
    "Dhuritha Nivarini",
    "Dhurjatipriya",
    "Dhurth Kyaya",
    "Dhurvangi",
    "Dhwaitha Panchamam",
    "Dhwajathi Kriya",
    "Dhyuthi Mala",
    "Dileepika",
    "Dinakara Ganthi",
    "Dipakam",
    "Divya Bauli",
    "Divya Bharanam",
    "Divya Gandharam",
    "Divya Kunthalam",
    "Divya Manjula",
    "Divya Sena",
    "Divya Tarangini",
    "Divyamathi",
    "Donga",
    "Douriyani",
    "Druvana Priya",
    "Duni Binna Shadjam",
    "Durbar",
    "Durga",
    "Dwaitha Chintamani",
    "Dwaitha Paripurni",
    "Dwajonnatha",
    "Dwandhothpala",
    "Dweepavathi",
    "Dwigandhara Bhushani",
    "Dwijakriya",
    "Dwijavanthi",
    "Dwikirani",
    "Dwimukha Priya",
    "Dwirata Kamini",
    "Dwithanandi",
    "Dwitheeya Panchamam",
    "E",
    "Easwari",
    "Eka Swarupi",
    "Ekaaneeka",
    "Ekagrani",
    "Ekakshari",
    "Ekaleela",
    "Ekamban",
    "Ekandholi",
    "Elakshari",
    "Elaprabhavam",
    "Enanka Manohari",
    "Esa Manohari",
    "Esa Priya",
    "Esandholi",
    "G",
    "Gaana Mayuri",
    "Gaeta Natani",
    "Gaga Rajitha",
    "Gagana Bhavani",
    "Gagana Bhoopalam",
    "Gagana Gandhari",
    "Gagana Kusumavali",
    "Gagana Mayuri",
    "Gagana Mohini",
    "Gagana Ranjani",
    "Gaganadhari",
    "Gaganambari",
    "Gaja Gowri",
    "Gaja Saari",
    "Gaja Sri",
    "Gaja vilasitha",
    "Gajanandini",
    "Gajavardhana",
    "Gama Bharani",
    "Gamaka Kriya",
    "Gamaka Priya",
    "Gamaka Samantham",
    "Gamakyam",
    "Gamana Bhaskara",
    "Gamana Kriya",
    "Gamana Lalitha",
    "Gamana Nirmala",
    "Gamana Tarangini",
    "Gambeerya Goshini",
    "Gambhira Ranjani",
    "Gambhira Vasantha",
    "Gambhirini",
    "Gambira Hindolam",
    "Gambiravani",
    "Gambirya Nattai",
    "Gana Bhushani",
    "Gana Lolam",
    "Gana Pratapa",
    "Gana Priya",
    "Gana Ranjani",
    "Gana Sakha",
    "Gana Sobhitham",
    "Gana Suprabhata",
    "Gana Swabhavam",
    "Gana Tarangini",
    "Ganalalitha",
    "Ganana Priya",
    "Gananayaki",
    "Ganandholika",
    "Ganangi",
    "GanaPinadhi",
    "Ganasabha",
    "Ganasamavarali",
    "Ganavarithi",
    "Ganavarshini",
    "Ganavasantham",
    "Ganavathi",
    "Ganda Dhruma",
    "Gandarva Narayani",
    "Gandarvam",
    "Gandhara Panchamam",
    "Gandhara Priya",
    "Gandhara Thola",
    "Gandharam",
    "Gandharva Kannada",
    "Gandharva Manohari",
    "Ganga Tarangini",
    "Gangai Priyan",
    "Ganga",
    "Gangalan",
    "Gangaradhwani",
    "Ganitha Vinodhini (Gunitha Vinodhini)",
    "Gantana",
    "Gantaravam",
    "Gantavali",
    "Garbha Dhwaja",
    "Garbha Leela",
    "Garbha Sardula",
    "Garudaadri",
    "Garuda Priya",
    "Garuda Varali",
    "Garuda Vardhini",
    "Garudadhwani",
    "Garva Manjari",
    "Gauda Malak",
    "Gauda Mallar",
    "Gauda Sarang",
    "Gaula Gandhari",
    "Gaula Panchamam",
    "Gaula Revagupti",
    "Gaula",
    "Gauli Panthu",
    "Gaund Giri",
    "Gauri Lalitha",
    "Gauri Shankar",
    "Gauri Velavali",
    "Gauri",
    "Gavathi",
    "Gayaka Lapini",
    "Gayaka Mandani",
    "Gayaka Ranjani",
    "Geervana Pada",
    "Geervani",
    "Geetamohini",
    "Geetha lambana",
    "Geetha Murthi",
    "Geetha Priya",
    "Geethi Kirani",
    "Geya Charadharini",
    "Geya Hejjejjee",
    "Ghagana Sarasiruha",
    "Ghana Jagana",
    "Ghana Kelini",
    "Ghana Kesi",
    "Ghana Shyamala",
    "Ghana Sindhu",
    "Ghanashyamalangi",
    "Ghandara Bauli",
    "Ghandara Gaula",
    "Ghandha Madhana",
    "Ghanta",
    "Ghantarava",
    "Ghantaravan",
    "Gharava Simhala",
    "Ghosha Vinodhini",
    "Ghoshini",
    "Ghoshkari",
    "Giri Dharini",
    "Giri Kunthali",
    "Giridhara",
    "Girija",
    "Girikarnika",
    "Girisa Priya",
    "Giriya Bharana",
    "Gomaatha",
    "Gnana Bhodini",
    "Gnana Lola",
    "Gnana Valli",
    "Gnanadhayaki",
    "Gnanamani",
    "Gnanamurthi",
    "Gnanappan",
    "Gnanaswarupini",
    "Gnanayurthi",
    "Gobinam",
    "Godharshini",
    "Godavari",
    "Gokula Murthi",
    "Gomandala",
    "Gomethaga Priya",
    "Gomukhi",
    "Gomurthikam",
    "Gopathi (Gomathi)",
    "Gopi Kamboji",
    "Gopika Kusumam",
    "Gopika Manoranjani",
    "Gopika Thilakam",
    "Gopika Vasantham",
    "Gopikabaranam",
    "Gopriya",
    "Gosha Manjari",
    "Goshpani",
    "Gothrari",
    "Govardhani",
    "Govinda Dhanyasi",
    "Govinda Narayani",
    "Govindambini",
    "Gowla Chandrika",
    "Gowlamalavi",
    "Gowri Bangala",
    "Gowri Kriya",
    "Gowri Maruva",
    "Gowri Nishada",
    "Gowri Panthu",
    "Gowri Seemanti",
    "Gowri Vasantha",
    "Gowrigandhari",
    "Gowthami",
    "Grandha Tarangani",
    "Greeshmavali",
    "Grihanambari",
    "Grutchi",
    "Guha Baranam",
    "Guha Manohari",
    "Guha Priya (Guna Priya)",
    "Guha Ranjani",
    "Guhan",
    "Guhya Dhyuthi",
    "Gumma Kambhoji",
    "Gummavali",
    "Gumya Dhyuthi",
    "Guna Bhushani",
    "Gunasindhu",
    "Gunavathi",
    "Gundakriya",
    "Gurjari",
    "Guru Dasan",
    "Guru Jyothi",
    "Guru Priya",
    "Gurudesya",
    "Gurunatha Priya",
    "Guruparan",
    "Guruprakasa",
    "H",
    "Hahori",
    "Haimavathi",
    "Hala Mukhi",
    "Halaktha Bharanam",
    "Halayudha Priya",
    "Hamir Kalyani",
    "Hamsa Bhashani (Hamsa Bhushani)",
    "Hamsa Bhoopalam",
    "Hamsa Bhoshani",
    "Hamsa Bhramari",
    "Hamsa Bhushavali",
    "Hamsa Deeparam",
    "Hamsa Deepika",
    "Hamsa Gamani",
    "Hamsa Gandarvam",
    "Hamsa Gandhari",
    "Hamsa Gantana",
    "Hamsa Gantarava",
    "Hamsa Geervani",
    "Hamsa Giri",
    "Hamsa Gotmana",
    "Hamsa Kalyani",
    "Hamsa Kambhoji",
    "Hamsa Kosali",
    "Hamsa Latha",
    "Hamsa Manjari",
    "Hamsa Nandana",
    "Hamsa Narayani",
    "Hamsa Natani",
    "Hamsa Neelambari",
    "Hamsa Nibhogi",
    "Hamsa Nisari",
    "Hamsa Panchamam",
    "Hamsa Prabhavali",
    "Hamsa Priya",
    "Hamsa Rasali",
    "Hamsa Rupini",
    "Hamsa Sreni",
    "Hamsa Varithi",
    "Hamsa Velavali",
    "Hamsa Vinodini",
    "Hamsa",
    "HamsaBhogi",
    "Hamsadwani",
    "Hamsanadam",
    "Hamsanandi",
    "Hamveeru",
    "Hanki Ghantarava",
    "Hanokaha",
    "Hara Bhushani",
    "Hara Manohari",
    "Hara Nandana",
    "Hara Vardana",
    "Haradharini",
    "Haraenapi",
    "Hari Kedara Gaula",
    "Hari Nakshi",
    "Hari Narayani",
    "Hari Nattai",
    "Hari Prakasa",
    "Hari Priya",
    "Harichandra Priya",
    "Haridharba",
    "Haridhasa Priya",
    "Harikedar",
    "Harini",
    "Haritha Priya",
    "Harsha Kapi",
    "Hasa Manjari",
    "Hasthini",
    "Hasya Bhushani",
    "Hasya Deepam",
    "Hataka Bharanam",
    "Hataka Varali",
    "Hatakangi",
    "Hatikangi",
    "Hayagathi",
    "Hejejjee Isari",
    "Hela Prabhata",
    "Hema Bhushani",
    "Hema Karahara Priya",
    "Hema Mandara",
    "Hema Pingala",
    "Hema Priya",
    "Hema Saranga",
    "Hema Vahini",
    "Hemakriya",
    "Hemalatha",
    "Hemambari",
    "Hemandini",
    "Hemangani",
    "Hemangi",
    "Hemant",
    "Hemarnava",
    "Henavali",
    "Heramba Priya",
    "Heyangavana",
    "Himaja",
    "Himangi",
    "Himavaluka",
    "Himavantika",
    "Himavardhani",
    "Himavilasini",
    "Hindol",
    "Hindola Desakshi",
    "Hindola Desika",
    "Hindola Durbar",
    "Hindola Gamini",
    "Hindola Kannada",
    "Hindola Kapi",
    "Hindola Malavi",
    "Hindola Mohanam",
    "Hindola Nayaki",
    "Hindola Saranga",
    "Hindola Saveri",
    "Hindola Vasantham",
    "Hindolam",
    "Hindu Kirvani",
    "Hindustham Behag",
    "Hindusthani Asaveri",
    "Hindusthani Kapi",
    "Hinkari",
    "Hira Dharini",
    "Hiradhini",
    "Hiranya Kriya",
    "Hiranya Lalitha",
    "Hitha Bhashini",
    "Hitha Priya",
    "Hothrari",
    "Hrudha Kamali",
    "Hrudha Kanthini",
    "Hrungara Dhwani",
    "Huseni",
    "Huthamathi",
    "Huttari",
    "I",
    "Idaikkan",
    "Ilakanti",
    "Inakara Priya",
    "Inavardhini",
    "Indalam",
    "Indhra Dhanu",
    "Indhra Kalam",
    "Indhra Nilam",
    "Indhu Bhogi",
    "Indhu Dhanyasi",
    "Indhu Ganthi",
    "Indhu Kannada",
    "Indhu Kausika (Indhu Gaulika)",
    "Indhu Kesari",
    "Indirani",
    "Indra Bharanam",
    "Indra Vamsa",
    "Indra Vardhana",
    "Indrapriya",
    "Indu Dhavali",
    "Indu Ghantarava",
    "Indu Ghantaravam",
    "Indu Kirvani",
    "Indu Priya",
    "Indu Saranganata",
    "Indumathi",
    "Indusheethala",
    "Innisai Diwakaran",
    "Isa Gowla",
    "Isagiri",
    "Isanan",
    "J",
    "Jaga Bharanam",
    "Jagadamba",
    "Jagadambari",
    "Jagadheeswari",
    "Jagamani",
    "Jagan Gana",
    "Jagan Manohari",
    "Jagan Mohana",
    "Jagan Mohanam",
    "Jaganmatha",
    "Jaganmohini",
    "Jagasu",
    "Jagatpari",
    "Jajalika",
    "Jajivasantha",
    "Jala Manjari",
    "Jala Sugandhi",
    "Jalaja Mukhi",
    "Jalaja Vasini",
    "Jalajavathi",
    "Jalakesari",
    "Jalamika",
    "Jalaprabhava",
    "Jalavu",
    "Jalodadi",
    "Jalodharam",
    "Jambu Kriya",
    "Jana Ranjani",
    "Jana Thodi",
    "Jananandhi",
    "Jananandini",
    "Janandolika",
    "Janani",
    "Janarakshani",
    "Janasa Ranjani",
    "Janasammodini",
    "Janavarali",
    "Janavi",
    "Jangla Raga",
    "Janjuti",
    "Jankara Bramari",
    "Jankara Priya",
    "Jankara Seela",
    "Jankaravani (Jankaramani)",
    "Jankari",
    "Janonnadi",
    "Janudwaya",
    "Janya Thodi",
    "Japaneeya",
    "Jarangi",
    "Jarapunjari",
    "Jaskavali",
    "Jatadhari",
    "Javanika",
    "Jaya Bharanam",
    "Jaya Bharani",
    "Jaya Bhavani (Bavani)",
    "Jaya Chudamani",
    "Jaya Manjari",
    "Jaya Manohari",
    "Jaya Mohana",
    "Jaya Narayani",
    "Jaya Neelaveni",
    "Jaya Rama",
    "Jaya Samavardhini",
    "Jaya Saranga",
    "Jaya Saraswathi",
    "Jaya Sekara",
    "Jaya Srikanthi",
    "Jaya Sukha",
    "Jaya",
    "Jayakshari",
    "Jayanandini",
    "Jayantha Sena",
    "Jayanthasri",
    "Jayasaveri",
    "Jayasindhu",
    "Jayasri",
    "Jayasuddha Malavi",
    "Jayavani",
    "Jayavelavali",
    "Jeenavalli",
    "Jeenavarali",
    "Jeevan Thini",
    "Jeevanpuri",
    "Jeevanthika",
    "Jeevaranjani",
    "Jeevaratna Bhushani",
    "Jeevika Vasantham",
    "Jekarnika",
    "Jindu",
    "Jingla Bairavi",
    "Jingla",
    "Jogi Bairavi",
    "Jogi",
    "Josila",
    "Jothispathi",
    "Jothsnapriya",
    "Jouda Gandhari",
    "Jujahuli (Jujavali)",
    "Jujavanthi",
    "Julavu",
    "Jushan Gada",
    "Jutalaka",
    "Jwala Kesari",
    "Jwalika",
    "Jyothi Raga",
    "Jyothi Ranjani",
    "Jyotish Mathi",
    "K",
    "Kaalika",
    "Kaamari Priya",
    "Kacha Raga",
    "Kadana Kuthuhalam",
    "Kadana",
    "Kadaram",
    "Kaddalam",
    "Kadhambini",
    "Kadyutha Ganthi",
    "Kaikavasi",
    "Kailayali",
    "Kaisika",
    "Kaivasi",
    "Kaiveni",
    "Kakali",
    "Kakavasanth",
    "Kala Bhogi",
    "Kala Murthi",
    "Kala Nirnika",
    "Kala Swarupi",
    "Kala Vahula",
    "Kalabharana",
    "Kaladharani",
    "Kalahamsa Gamini",
    "Kalahamsa",
    "Kalakamadi",
    "Kalakanta Dhwani",
    "Kalakanti",
    "Kalanidhi",
    "Kalasaveri",
    "Kalathi",
    "Kalavali",
    "Kalavasantham",
    "Kalavathi",
    "Kalharu",
    "Kalika Vasantham",
    "Kaliki",
    "Kalinda Janmadhini",
    "Kalindaja",
    "Kalindhi",
    "Kalkada",
    "Kallola Bangala",
    "Kallola Saveri",
    "Kallola",
    "Kaltada",
    "Kalthava Priya",
    "Kalyana Dayini",
    "Kalyana Gowri",
    "Kalyana Kesari",
    "Kalyana Tarangini",
    "Kalyana Vahini",
    "Kalyana Vasantham",
    "Kalyani",
    "Kama Prabha",
    "Kamadwajitha",
    "Kamaji",
    "Kamakya",
    "Kamala Baranam",
    "Kamala Manohari",
    "Kamala Mohana",
    "Kamala Narayani",
    "Kamala Nirutham",
    "Kamala Panchamam",
    "Kamala Tarangini",
    "Kamala Vasantham",
    "Kamala Vilasitha",
    "Kamala Vurdhi",
    "Kamala",
    "Kamalapani",
    "Kamalapathi",
    "Kamalaptha Priya",
    "Kamalasana Priya",
    "Kamalasana",
    "Kamalasini",
    "Kamalaveni",
    "Kamalini",
    "Kamalotharam",
    "Kamalu",
    "Kamaranjani",
    "Kamarupi",
    "Kamas",
    "Kamatadhwaja",
    "Kamboji",
    "Kamini Priya",
    "Kamini Ritigaula",
    "Kamini",
    "Kamoda Khadgadharini",
    "Kamodha",
    "Kampadhwaja",
    "Kampavathi",
    "Kamsari",
    "Kamya",
    "Kanada",
    "Kanajagana",
    "Kanaka Bhavani",
    "Kanaka Bhushavali",
    "Kanaka Chandrika",
    "Kanaka Deeparam",
    "Kanaka Giri",
    "Kanaka Jyotishmati",
    "Kanaka Kanti",
    "Kanaka Keervani",
    "Kanaka Kusumavali",
    "Kanaka Leela",
    "Kanaka Mandana",
    "Kanaka Nasamani",
    "Kanaka Nirmada",
    "Kanaka Ranjani",
    "Kanaka Rasali",
    "Kanaka Sabhai",
    "Kanaka Simharavam",
    "Kanaka Srikanti",
    "Kanaka Varshini",
    "Kanaka Vasantham",
    "Kanaka Vasantika",
    "Kanaka",
    "Kanakadri",
    "Kanakambari",
    "Kanakavarali",
    "Kanavahini",
    "Kancha Bava Priya",
    "Kanchana Mala",
    "Kanchanambari",
    "Kanchanangi",
    "Kanchanavathi",
    "Kanchani (Kanakachari)",
    "KanchaPunji",
    "Kanchuki",
    "Kandajwalana",
    "Kandarapriya",
    "Kandarvamanohari",
    "Kandavali",
    "Kandha Dhruma",
    "Kanjari",
    "Kankanalankari",
    "Kannada Bangala",
    "Kannada Bhogi",
    "Kannada Bhomani",
    "Kannada Deepara",
    "Kannada Durbar",
    "Kannada Kurinji",
    "Kannada Mallaru",
    "Kannada Maruva",
    "Kannada Matta",
    "Kannada Panchamam",
    "Kannada Salavi",
    "Kannada Saurashtram",
    "Kannada Velavali",
    "Kannada",
    "Kannadagaula",
    "Kannan",
    "Kantarakapani",
    "Kanteeravam",
    "Kantha Manjari",
    "Kantha Rakshasa",
    "Kantha Rathna",
    "Kanthamathi",
    "Kanthi Swarupini",
    "Kanthi",
    "Kanthimathi",
    "Kanyavidhana",
    "Kapi Jingla",
    "Kapi Narayani",
    "Kapi",
    "Kapila",
    "Kapriya Nayakam",
    "Karadwathi",
    "Karaga",
    "Karajavali",
    "Karala Dhari",
    "Karalari",
    "Karani",
    "Karanjakam",
    "Karanjini",
    "Karathoya",
    "Karava Simhala (Samavarali)",
    "Karavani",
    "Kargeswari",
    "Karikadya",
    "Karjam",
    "Karmavu",
    "Karmughavathi",
    "Karna Bhushani",
    "Karna Ranjani",
    "Karnamanjari",
    "Karnamrutha Varshini (amrutha Varshini)",
    "Karnataka Andhali",
    "Karnataka Behag",
    "Karnataka Bhoga",
    "Karnataka Devaghandari",
    "Karnataka Gaula",
    "Karnataka Kadambi",
    "Karnataka Kamas",
    "Karnataka Kannada",
    "Karnataka Kapi",
    "Karnataka Manjari",
    "Karnataka Saranga",
    "Karnataka Tharangini",
    "Karnatakasurati",
    "Karnika Bhushani (Kanaka Bhushani)",
    "Karnika Dhari",
    "Karnika Ranjani",
    "Karpura Bharani",
    "Karpuram",
    "Karuna Priya",
    "Karunakaran",
    "Karunakari",
    "Karunipriya",
    "Karuvali",
    "Karya Chandrika",
    "Karya Mathi",
    "Kashmira",
    "Kashyapi",
    "Kasi Latha",
    "Kasiramakriya",
    "Kathyayini",
    "Katinya",
    "Katitha",
    "Kaumari",
    "Kaumathi",
    "Kauranjam",
    "Kausika Dhwani",
    "Kausikam (Bairavi)",
    "Kausilaka",
    "Kavanda",
    "Kavya Chitra",
    "Kayajapriya",
    "Kazhiyan",
    "Kedara Chaya",
    "Kedara Gaula",
    "Kedara Manjari",
    "Kedara Nata",
    "Kedaram",
    "Keechakari",
    "Keeranavali",
    "Keerani",
    "Keerthi Bhanu",
    "Keerthi Priya",
    "Keerthi Vijaya",
    "Keervanapriya",
    "Keervani",
    "Kendha Vikshepam",
    "Kereeda Mathi",
    "Kesa Bauli",
    "Kesara Nata",
    "Kesara",
    "Kesarangi",
    "Kesarava Loka",
    "Kesaravali",
    "Kesari Kriya",
    "Kesari",
    "Ketha Kangkusha",
    "Kethaka Priya",
    "Kethanavali",
    "Khadga Dharini",
    "Khadhyotha Priya",
    "Khantha Dhanyasi",
    "Khatgapriya",
    "Kilavali",
    "Kinnaravali",
    "Kinnaresa Priya",
    "Kinnari",
    "Kiradharini",
    "Kirana Bhaskari",
    "Kiranda Tharangini",
    "Kirudasi",
    "Kiti Mayura",
    "Kodai Bhoopalam",
    "Kodunugam",
    "Kokila Bhashini",
    "Kokila Deepakam",
    "Kokila Deeparam",
    "Kokila Deeptham",
    "Kokila Dhwani",
    "Kokila Gandaruva",
    "Kokila Kamavardhani",
    "Kokila Keeravani",
    "Kokila Nandi",
    "Kokila Nata",
    "Kokila Panchamam",
    "Kokila Pratapam",
    "Kokila Swaravali",
    "Kokila Vardhani",
    "Kokilam",
    "Kokilaravam",
    "Kokilavarali",
    "Kolahalam",
    "Kolangasha",
    "Kolapani",
    "Kolikavichitra",
    "Kolli Kappanam",
    "Kolli",
    "Komala Vilasitha",
    "Komalangi",
    "Komali",
    "Kosala",
    "Kothmari",
    "Kottani (Gottani)",
    "Koumoda",
    "Kousthuba Priya",
    "Kovindambini",
    "Kowmodhakam",
    "Kowsika Lalitha",
    "Kowsika",
    "Krandha Tarangini",
    "Krindha Vikshepam",
    "Krishnaveni",
    "Kriya Viraman",
    "Kriyavathi",
    "Krouncham",
    "Kshanapriya (Kshanaprabha)",
    "Kshanika",
    "Kshararnava",
    "Kshemakari",
    "Kshepa",
    "Kshepini",
    "Kshith Rakshi",
    "Kshoni",
    "Kuber Priya",
    "Kuberan",
    "Kubja Viratha",
    "Kucha Vahini",
    "Kuchamargini",
    "Kuchiramani",
    "Kujan Mohana",
    "Kujhan",
    "Kukuda Sri",
    "Kukutha",
    "Kula Bhushani",
    "KulaPavithri",
    "Kumara Dhyuthi",
    "Kumara Leela",
    "Kumara Ranjani",
    "Kumara Vilasitha",
    "Kumarapriya",
    "Kumbini",
    "Kumuda Kriya",
    "Kumuda Prabha",
    "Kumuda Priya",
    "Kumudabaranam",
    "Kumudha Modha",
    "Kumudini",
    "Kunda Mulika",
    "Kunja Malini",
    "Kunjana Komalam",
    "Kunjaradhwani",
    "Kunkumambari",
    "Kuntala Bhavani",
    "Kuntala Dhanyasi",
    "Kuntala Simharam",
    "Kunthala Bhogi",
    "Kunthala Deeparam",
    "Kunthala Gantana",
    "Kunthala Kambhoji",
    "Kunthala Keervani",
    "Kunthala Kusumavali",
    "Kunthala Rama",
    "Kunthala Ranjani",
    "Kunthala Saranga",
    "Kunthala Srikanti",
    "Kunthala Sriranjini",
    "Kunthala Swaravali",
    "Kunthala Varali",
    "Kunthala",
    "Kurandalochani",
    "Kuresha",
    "Kurinji (Harikamboji)",
    "Kurinji Chaya",
    "Kurinji Vijayam",
    "Kuru Gadhya",
    "Kushya Keta Priya",
    "Kusuma Bhavani",
    "Kusuma Bhogi",
    "Kusuma Bramari",
    "Kusuma Chandrika",
    "Kusuma Dharini",
    "Kusuma Jyotishmati",
    "Kusuma Kallola",
    "Kusuma Marutha",
    "Kusuma Priya",
    "Kusuma Raja",
    "Kusuma Ranjani",
    "Kusuma Sarang",
    "Kusuma Vichitra",
    "Kusumakara",
    "Kusumangi",
    "Kusumavali",
    "Kuthuhalam",
    "Kutumbini",
    "Kuvalaya Bharanam",
    "Kuvalaya Priya",
    "Kuvalayanandam",
    "Kuvalayanandi",
    "Kuzhagan",
    "L",
    "Lakshmana Kuntali",
    "Lakshmi",
    "Lalitha Gandharvam",
    "Lalitha Gauri",
    "Lalitha Ghandari",
    "Lalitha Kosala",
    "Lalitha Kriya",
    "Lalitha Manohari",
    "Lalitha Maruva",
    "Lalitha Panchamam",
    "Lalitha Priya",
    "Lalitha Simharavam",
    "Lalitha Srikanti",
    "Lalitha Srikarni",
    "Lalitha thodi",
    "Lalitha",
    "Lalithadeepakam",
    "Lalithangi",
    "Languli",
    "Lasaki",
    "Lasya Priya",
    "Latantapriya",
    "Latha Hitha",
    "Latha Manjari",
    "Latha Mathi",
    "Lathamani",
    "Latharlathika",
    "Lathathanvi",
    "Lathi Kanthi",
    "Lavana Varidhi",
    "Lavangi",
    "Lavantika",
    "Lavanya",
    "Lavanyavathi",
    "Laya Madhya",
    "Leechi Salaka",
    "Leelaranjani",
    "Leelatarangini",
    "Leelavati",
    "Leelavinodhini",
    "Leena Mathi",
    "Leepthali",
    "Loka Pratapa",
    "Loka Priya",
    "Loka Ranjani",
    "Lokadeeparam",
    "Lokanayakhi",
    "Lokendra Mani",
    "Lolakshi",
    "Lolamba",
    "Lolangi",
    "Lolaski",
    "M",
    "Maadha Ranjani",
    "Maahuri",
    "Maathuranjani",
    "Maboni",
    "Madana Bhuthi",
    "Madana Marutha",
    "Madana Mohini",
    "Madana Rekha",
    "Madana",
    "Madanambari",
    "Madanojwala",
    "Madhava Chandrika",
    "Madhava Kalyan",
    "Madhava Kalyani",
    "Madhava Manohari",
    "Madhava Priya",
    "Madhava Sri",
    "Madhavi",
    "Madhrudhruma",
    "Madhu Jankari",
    "Madhukari",
    "Madhulika",
    "Madhumalathi",
    "Madhumat Sarang",
    "Madhupathi",
    "Madhuranjani",
    "Madhurya",
    "Madhuvanthi",
    "Madhya Kokila",
    "Madhyama Varali",
    "MadhyaMavathi",
    "Madura Lapa",
    "Magathi",
    "Magha Dhana",
    "Magha Tarangini",
    "Maghadhari",
    "Maghadhasri",
    "Maghava",
    "Maha Nandi",
    "Maha Sukavathi",
    "Mahadevan",
    "Mahalikam",
    "Mahanandini",
    "Mahati",
    "Mahila",
    "Mahuri",
    "Mahurim",
    "Mahurin",
    "Maithra Pavini",
    "Makara Nandana Priya",
    "Makarantha Priya",
    "Makarayudham",
    "Makuta Dharini",
    "Makutasri",
    "Mala Dharini",
    "Mala Kosh",
    "Malahari",
    "Malar",
    "Malarone",
    "Malathi Priya",
    "Malava Gandhari",
    "Malava Panchamam",
    "Malava Sindhu",
    "Malavasri",
    "Malavi Sri",
    "Malavi",
    "Malawagaula",
    "Malaya Jalaepini",
    "Malayala Kurinji",
    "Malayamarutham",
    "Malayangi",
    "Malhar",
    "Malini Makarandam",
    "Malini",
    "Malkali",
    "Malkimpuri",
    "Mallaru",
    "Mallika Vasantham",
    "Mallikamodha",
    "Mamangala Desikam",
    "Mamsi",
    "Mana Herali",
    "Manabharanam",
    "Manadhruva",
    "Manarupi",
    "Manasija Priya",
    "Manasika Gamini",
    "Manavali",
    "Manavi",
    "Mand",
    "Mandakini",
    "Mandala Grihani",
    "Mandamari",
    "Mandana Kirapani",
    "Mandara Gaula",
    "Mandasena",
    "Mandha Hasini",
    "Mandha Krantha",
    "Mandhari",
    "Mandini",
    "Mangala Chandrika",
    "Mangala Dhanyasi",
    "Mangala Gowri (Mangala Gowla)",
    "Mangala Kaisika",
    "Mangala Kari",
    "Mangala Nayaki",
    "Mangala Prada",
    "Mangala Priya",
    "Mangalabhushani",
    "Mangaladesika",
    "Mangaladwani",
    "Mangayarkarasi",
    "Mani Manjari",
    "Mani Rangu",
    "Manimanda",
    "Manimaya",
    "Manini",
    "Manjari",
    "Manji Vasantham",
    "Manji",
    "Manjula",
    "Manmada Latha",
    "Manmagan",
    "Mannankari",
    "Manoharan",
    "Manohari",
    "Manolayam",
    "Manorama",
    "Manoranjani",
    "Manya",
    "Mara Herali",
    "Mara Jayanthi",
    "Mara Narayani",
    "Mara Tharangini",
    "Maragadha Bhushani",
    "Maragadha Prabha",
    "Maragadha Sri",
    "Marala Gamini",
    "Maraladhvani",
    "M",
    "Maran",
    "Maravi",
    "Maravipramana",
    "Marga Badra",
    "Marga Desi",
    "Marga Jayanthi",
    "Marga Mohini",
    "Marga Pratapa",
    "Marga Sanjivini",
    "Margadesika",
    "Margha Hindolam",
    "Marghavi",
    "Margini",
    "Marichaka",
    "Marla",
    "Marmakshari (Marmakesari)",
    "Marthanda Priya",
    "Marupi",
    "Maruthi",
    "Maruva Bangala",
    "Maruva Chandrika",
    "Maruva Desi",
    "Maruva Desika",
    "Maruva Dhanyasi",
    "Maruva Gaula",
    "Maruva Gowri",
    "Maruva Kannada",
    "Maruva Lalitha",
    "Maruva Narayani",
    "Maruva Ranjani",
    "Maruva Saranga",
    "Maruva Simantha",
    "Maruva Vasantham",
    "Maruva",
    "Mathangagamini",
    "Matta Gandhari",
    "Mattakasini",
    "Mattha Bhavali",
    "Mattha Koki",
    "Mattha Kokila",
    "Matti Mavali",
    "Mau Jeevakam",
    "Maudha Dhanyasi",
    "Mauna Suganthi",
    "Mausevitha",
    "Maya Lalith",
    "Maya Malavagaula",
    "Maya Pradipam",
    "Maya Tarangini",
    "Maya Vasantha",
    "Maya Vinodini",
    "Mayadharini",
    "Mayadravila",
    "Mayarupini",
    "Mayaswarupini",
    "Mayura Dhwani (Andolika)",
    "Mayura Giri",
    "Mayura Mani",
    "Mayura Mauli",
    "Mayura Sari",
    "Mayura Saveri",
    "Mayura Vasantham",
    "Mayuran",
    "Mecha Bangala",
    "Mecha Bauli",
    "Mecha Gandhari",
    "Mecha Kangi",
    "Mecha Manohari",
    "Mecha Narayani",
    "Mecha Nilambari",
    "Mecha Putri",
    "Mecha Saveri",
    "Mechakambhoji",
    "Mechakannada",
    "Meenalochani",
    "Mega Bandhu",
    "Mega",
    "Megatarangini",
    "Megha Mallaru",
    "Megha Ranji",
    "Megha Syamala",
    "Meghadha Sri",
    "Megharagakurinji",
    "Meghavali",
    "Melaga",
    "Meru Nanthini",
    "Mitha Bhashita",
    "Mithra Kirani",
    "Mithra Ranjani",
    "Modhakam",
    "Mohana Chandrika",
    "Mohana Dhwani",
    "Mohana Kaisika",
    "Mohana Kalyani",
    "Mohana Kurinji",
    "Mohana Nattai",
    "Mohana Varali",
    "Mohana Varithi",
    "Mohanam",
    "Mohanamallaru",
    "Mohanangi",
    "Moksha Dayini",
    "Moocha Dhwani",
    "Moudha Dhanyasi",
    "Mowlika Dhruma",
    "Mrigakshi",
    "Mrigendra",
    "Mrigendramadhyamam",
    "Mrudani",
    "Mruganandana",
    "Mucha Sudhani",
    "Mudhumagan",
    "Mudhuvan",
    "Muhurtha Dhanyasi",
    "Mukha Priya",
    "Mukha Shyamala",
    "Mukhari",
    "Mukkanni",
    "Mukthamani",
    "Mukthambari",
    "Mukthangi",
    "Mukthavali",
    "Mukti Dayini",
    "Mukunda Baranam",
    "Mukunda Kalyani",
    "Mukunda Manohari",
    "Mukunda Priya",
    "Mukurangi",
    "Mukuratha Kapola",
    "Multani (Gamaka Samantham)",
    "Murajavadani",
    "Murthi Vasantham",
    "Murthi",
    "Murthika Darpanam",
    "Muthiradharini",
    "N",
    "Nabhava Madhya",
    "Nabomani",
    "Nabomargini",
    "Nacharam",
    "Nada Brahmam",
    "Nada Mukhari",
    "Nada Sanjeevi",
    "Nadarupi",
    "Nadha Bramari",
    "Nadha Chintamani",
    "Nadha Giri",
    "Nadha Kalyani",
    "Nadha Manjari",
    "Nadha Murthi",
    "Nadha Nali",
    "Nadha Priya",
    "Nadha Swarupi",
    "Nadha Tali",
    "Nadha Tarangini",
    "Nadha Varangini",
    "Nadha Vinodini",
    "Nadhalalitha",
    "Nadhanamakriya",
    "Nadharupini",
    "Naga Bharanam",
    "Naga Bhashini",
    "Naga Bhogi",
    "Naga Bhoopalam",
    "Naga Bhushani",
    "Naga Bhushini",
    "Naga Chandrika",
    "Naga Choodamani",
    "Naga Deeparam",
    "Naga Deepika",
    "Naga Dhawali",
    "Naga Dhwani",
    "Naga Gandhari",
    "Naga Gandharvam",
    "Naga Gantana",
    "Naga Gupti",
    "Naga Hindolam (Nada Hindolam)",
    "Naga Jayanthi",
    "Naga Kalyani",
    "Naga Keervani",
    "Naga Kokila",
    "Naga Kunthali",
    "Naga Malini",
    "Naga Neelambari",
    "Naga Panchamam",
    "Naga Prabavali",
    "Naga Prakasini",
    "Naga Priyan",
    "Naga Saka",
    "Naga Samantham",
    "Naga Sarasiruha",
    "Naga Sisuritha",
    "Naga Sugandi",
    "Naga Tarangini",
    "Naga Vahini",
    "Naga Varidhi",
    "Nagagiri",
    "Nagajara",
    "Nagakurinji",
    "Nagamandalam",
    "Nagamani",
    "Nagaraja",
    "Nagari",
    "Nagaswarali",
    "Nagavalli",
    "Nagavarali",
    "Nagavasini",
    "Nagavelavali",
    "Nagha Bharani",
    "Nagonjini",
    "Naimapriya",
    "Nalika",
    "Nalikam",
    "Nalina Bhramari",
    "Nalina Hamsi",
    "Nalina Kanthi",
    "Nalina Kusumavali",
    "Nalina Mukhi",
    "Nalina Panchamam",
    "Nalina Shanthi",
    "Nalina Sukhi",
    "Nalola",
    "Nama Narayani",
    "Nama Prabha",
    "Namadesi",
    "Namagan",
    "Namanojwala",
    "Namavarali",
    "Nanbhan",
    "Nand",
    "Nandaherali",
    "Nandalaka",
    "Nandalaya",
    "Nandana Priya",
    "Nandana",
    "Nandanavali",
    "Nandavasutha",
    "Nandimuka",
    "Nandini",
    "Nanmugan",
    "Naradha Mukhari",
    "Naraji",
    "Narasa",
    "Narayanaadri",
    "Narayana Gaula",
    "Narayana Manohari",
    "Narayani Desakshi",
    "Narayani",
    "Nari Ritigowla",
    "Narmada",
    "Narthaki",
    "Nasa Manjari",
    "Nasamani",
    "Nasavathi",
    "Nata Vardhani",
    "Natabharanam",
    "Nataka Thodi",
    "Natana Deepakam",
    "Natana Deeparam",
    "Natana Mohanam",
    "Natana Priya",
    "Natana Velavali",
    "Natanarayani",
    "Natanavathi",
    "Natchatra Chudamani",
    "Natchatramala",
    "Nati Param",
    "Natika",
    "Natikai Mani",
    "Natta Mallaru",
    "Nattai",
    "Nattakurinji",
    "Nattapadai (Nattai)",
    "Nattaragam",
    "Nattiyoma",
    "Natya Bhushani",
    "Natya Dharana",
    "Natya Mangala",
    "Natya Manohari",
    "Natya Vardhini",
    "Nava Manohari",
    "Navabhasura",
    "Navagriha Mulika",
    "Navamani Chandrika",
    "Navaneetha Panchamam",
    "Navaplavi",
    "Navarasa Andhali",
    "Navarasa Bangala",
    "Navarasa Chandrika",
    "Navarasa Gandhari",
    "Navarasa Kalanidhi",
    "Navarasa Kannada",
    "Navarasa Kunthala",
    "Navarasa",
    "Navaratna Bhoshani",
    "Navaratna Vilasam",
    "Navasuthika",
    "Navroj",
    "Navukkarasu",
    "Nayaki",
    "Nayamathi",
    "Nayana Bhashini",
    "Nayana Ranjani",
    "Nediyone",
    "Needhi Kala",
    "Needhi Manjari",
    "Needhi Murthi",
    "Neela Prabha",
    "Neela Suri (Neela Mani)",
    "Neela Veni",
    "Neela",
    "Neelaadri",
    "Neelakanta Priya",
    "Neelambari",
    "Neelangi",
    "Neeli",
    "Neera Pratapa",
    "Neeraja Priya",
    "Neethi Kunthali",
    "Neethi Mallaru",
    "Nemanga",
    "Nemy",
    "Nepala Gaula",
    "Nepala",
    "Nepali",
    "Niga Manasa",
    "Nigama Gamini",
    "Nigama Sanchari",
    "Nigraha Mani",
    "Nihara",
    "Niharadri",
    "Nirajamani",
    "Niranjani",
    "Niravadya",
    "Nirja Ravana",
    "Nirjarini",
    "Nirmada",
    "Nirmala Gaula",
    "Nirmalan",
    "Nirmalangi",
    "Nirmitham",
    "Niroshta",
    "Nirudragiri",
    "Nirvana Vasantha",
    "Nirvani",
    "Nirvari",
    "Nirvika Modha",
    "Nisakaran",
    "Nishada Priya",
    "Nishadam",
    "Nishadi",
    "Nishkam",
    "Nitila Prakasini",
    "Nivaram",
    "Nruthya Kausika",
    "Nutha Bhashini",
    "Nutha Bhashitham",
    "Nuthana Chandrika",
    "O",
    "Om Suddha Ragam",
    "Omkara Ghoshini",
    "Omkara Kriya",
    "Omkara Swarupini",
    "Omkari",
    "Ooka Priya",
    "Oshadhi",
    "Ourya Sripriya",
    "Oushadeesa Priya",
    "P",
    "Padavai",
    "Padi",
    "Padma Bhavani",
    "Padma Gantana",
    "Padma Kesara",
    "Padma Mukhi",
    "Padma Soundarya",
    "Padma",
    "Padmakanthi",
    "Padmasitha",
    "Padmavali",
    "Padmavathi",
    "Padmini",
    "Pahadi",
    "Pahali",
    "Pahlika",
    "Paingala",
    "Pakasana Priya",
    "Paksuka Mana",
    "Pala Nandhini",
    "Palaranjani",
    "Palasi (Pushpalatika)",
    "Palika Vasantham",
    "Palika",
    "Palini",
    "Palladhi",
    "Pallava",
    "Panava Narasa",
    "Pancha Kottani",
    "Pancha Mukhi",
    "Pancha Murthi",
    "Pancha Rupi",
    "Panchali",
    "Panchalika",
    "Pancham Malakosh (Jayanthisri)",
    "Pancham",
    "Panchama lalitha",
    "Panchama Natta",
    "Panchama",
    "Panchamam (Ahiri)",
    "Panchasya Nandana",
    "Pandi",
    "Pankaeruha",
    "Pannavardhani",
    "Panthuvarali",
    "Panuvalatti",
    "Parabhruthavani",
    "Parai",
    "Parameshti",
    "Paranam",
    "Parandaman",
    "Parasara",
    "Parasu",
    "Parijatha",
    "Parimalanandi",
    "Parisuddha",
    "Parithi",
    "Parva Mani",
    "Parva Paavathi",
    "Parvatha Manjari",
    "Parvatham",
    "Parvathi",
    "Pasa Narayani",
    "Pasadam",
    "Pasupathi Priya",
    "Patalambari",
    "Pateera Dhwani",
    "Pateerava",
    "Pathaka",
    "Patiladri",
    "Patilarava",
    "Patolika",
    "Patta Deep",
    "Paura Prakasa",
    "Pavagan",
    "Pavana Vasantha",
    "Pavanakari",
    "Pavini",
    "Pavitri",
    "Payasvini",
    "Pazham Panzaram (Sankarabaranam)",
    "Pazhamthakka Raga",
    "Peethambari",
    "Penadhyuthi",
    "Penandholi",
    "Pendrula",
    "Peruran",
    "Phala Manjari",
    "Phala Ranjani",
    "Pika Dhwani",
    "Piloo",
    "Pinakini",
    "Pinchukan",
    "Pingavathi",
    "Pithrambari",
    "Pooja Bauli",
    "Poorna Swaravali",
    "Poorva Ramakriya",
    "Poorvadharsi",
    "Poshini",
    "Prabha Tarangini",
    "Prabhasa",
    "Prabhava",
    "Prabhavali",
    "Prabhavati",
    "Prabhoda Kada",
    "Prabhu Priya",
    "Pradeechi",
    "Pragnavathi",
    "Praguni",
    "Praharana Kalitha",
    "Prakara Ranjani",
    "Prameya",
    "Pramodhini (Giridharini)",
    "Pramodigathi",
    "Pramudita Vadana",
    "Pranava Priya",
    "Pranavakari",
    "Prapapanchasraya",
    "Prasanthi",
    "Prasenavali",
    "Prasthapana",
    "Pratapa Chintamani",
    "Pratapa Gamana",
    "Pratapa Hamsa",
    "Pratapa Kokilam",
    "Pratapa Natta",
    "Pratapa Rudri",
    "Pratapa Saranga",
    "Pratapa Sindhu",
    "Pratapa Varali",
    "Pratapa Vasantham",
    "Pratapa",
    "Prathapa Ranjani",
    "Pratheethi",
    "Prathi Bimba",
    "Prathi Hari",
    "Prathi Madhyamavati",
    "Prathithi",
    "Prati Madhyamam",
    "Pravala Jyothi",
    "Pravurthi",
    "Preethi Varuni",
    "Preyasi",
    "Prithivya Padmaka",
    "Prithvi",
    "Priya Dharsini",
    "Priya Virama",
    "Priyamvada",
    "Priyasri",
    "Pulasya",
    "Pulindika",
    "Pulomika",
    "Punithan",
    "Punjavali",
    "Punnaga Lalitha",
    "Punnaga Thodi",
    "Punnaga Varali",
    "Pur Kalyani",
    "Pura Purika",
    "Puradahana Priya",
    "Puranakam",
    "Puranan",
    "Puranirmai",
    "Purasuya",
    "PuriKalyani",
    "Purna Chandrika",
    "Purna Gandhari",
    "Purna Gowla",
    "Purna Kalanidhi",
    "Purna Kambhoji",
    "Purna Kousikam",
    "Purna Lalitha",
    "Purna Malini",
    "Purna Nattai (Chalanata)",
    "Purna Nishadam",
    "Purna Panchamam",
    "Purna Salavi",
    "Purna Shadjam",
    "Purna Shyamala",
    "Purnachandrika",
    "Purnamalavi",
    "Purno Daya",
    "Purva Barasu",
    "Purva Bhairavi",
    "Purva Gowla",
    "Purva Kalyani",
    "Purva Karnika",
    "Purva Mukhari",
    "Purva Varali",
    "Purvakannada",
    "Purvasindhu",
    "Purvi",
    "Purya",
    "Pushkarani",
    "Pushpa Latika",
    "Pushpa Manohari",
    "Pushpalalitha",
    "Pushpalata",
    "Pushpamani",
    "Pushpavasantham",
    "Puthrika",
    "Puttari",
    "R",
    "Raegupti",
    "Raga Bhogi",
    "Raga Chandrika",
    "Raga Chudamani",
    "Raga Kesari",
    "Raga Mallika",
    "Raga Pancharam",
    "Raga Pradipika",
    "Raga Pratapa",
    "Raga Vasantham",
    "Raga Vinodhini",
    "Raga",
    "Ragamanjari",
    "Ragamanohari",
    "Ragamurthi",
    "Ragasugandhi",
    "Ragavahini",
    "Raghu Leela",
    "Raja Ganthi",
    "Raja Kalyani",
    "Raja Manjari (Raja Mandari)",
    "Raja Manohari",
    "Raja Pradipika",
    "Raja Ranjini",
    "Raja Saranga",
    "Raja Sundari",
    "Rajachintamani",
    "Rajathavali",
    "Rajathilakam",
    "Rajavasyani",
    "Rajeswari",
    "Raktha Mathi",
    "Rakthakshi",
    "Rakthamadhavi",
    "Rakthi Mathi",
    "Rakti Margini",
    "Ram Bhavali",
    "Rama Chudamani",
    "Rama Kriya",
    "Rama Kunthali",
    "Rama Kusumavali",
    "Rama Latitha",
    "Rama Leala",
    "Rama Manjari",
    "Rama Manohari",
    "Rama Murthi",
    "Rama Narayani",
    "Rama Priya",
    "Rama Ranjani",
    "Rama Sadani",
    "Rama Varali",
    "Rama Vilasitha",
    "Ramagiri",
    "Ramakali",
    "Ramani",
    "Ramavathi",
    "Rambhavali",
    "Ramya Bhashini",
    "Ramya Mukhi",
    "Ramya Panchamam",
    "Ramya",
    "Ranga Kausthuba",
    "Ranga Leela",
    "Ranga Manohari",
    "Ranga Rohini",
    "Ranganayaki",
    "Rangavaili",
    "Rangavambari",
    "Ranjana Gowri",
    "Ranjana Kausthubam",
    "Ranjani",
    "Rasa Bhaskara",
    "Rasa Kalambika",
    "Rasa Prathapa",
    "Rasa Sindhu",
    "Rasa Vinodhini",
    "Rasagucha",
    "Rasakalanidhi",
    "Rasali (Karjavali)",
    "Rasalini",
    "Rasamanjari",
    "Rasavali",
    "Rasavarali",
    "Rasika Kalyan",
    "Rasika Ranjani",
    "Rathavali",
    "Rathi Pathi Priya",
    "Rathi Priya",
    "Rathi Sobhita",
    "Rathi",
    "Rathika",
    "Rathna Bhanu",
    "Rathna Bhoshani",
    "Rathnabharanam",
    "Rathnakarshini",
    "Rathnavari (Rathnavali)",
    "Ratinvaki",
    "Ratna Bharani",
    "Ratna Bhushani",
    "Ratna Garbha",
    "Ratna Jwalitha",
    "Ratna Kanthi",
    "Ratnajyothi",
    "Ratnakari",
    "Ratnamani",
    "Ratnambari",
    "Ratnapurna",
    "Raubyanayakam (Raubya)",
    "Raudavali",
    "Ravalika Leela",
    "Ravana Priya",
    "Ravi Dhyuthi",
    "Ravi Kirani",
    "Ravi Kriya",
    "Ravi Prabhavali",
    "Ravi Prathapi",
    "Ravi Priya (Raghu Piya)",
    "Ravi Sindhu",
    "Ravi Swarupi",
    "Ravichandrika",
    "Ravisatya",
    "Reethi Chandrika (Neethi Chandrika)",
    "Reka Ranjini",
    "Rekavati",
    "Relavasantha",
    "Rengathodi",
    "Renuka",
    "Reranjini",
    "Reva Gupti",
    "Reva Nattai",
    "Reva",
    "Revathi",
    "Rinkari",
    "Rishabavilas",
    "Rishabha Vahini",
    "Rishabhangi",
    "Rishi Kethu Priya",
    "Rishi Priya",
    "Rithi Gaula",
    "Rithu Vilas",
    "Rodhavali",
    "Rohana Kalyani",
    "Rohini",
    "Rolamba Dhwani",
    "Rolamba",
    "Rowdra Gandhari",
    "Ruchi Ramani",
    "Ruchi Rangi",
    "Rudhra Ghantaravam",
    "Rudra Desika",
    "Rudra Gandhari",
    "Rudra kesari",
    "Rudra Manjari",
    "Rudra Panchami",
    "Rudra Priya",
    "Rudra Saveri",
    "Rudrabhisheka",
    "Rudramani",
    "Ruhakam",
    "Rukma Dwaja",
    "Rukma Sandini",
    "Rukmambari",
    "Rukmangi",
    "Rupangi",
    "Rupavathi",
    "Rushabha",
    "S",
    "Saaghu",
    "Saarika",
    "Sabadyadi",
    "Sabha Vigraha",
    "Sadari",
    "Sadham",
    "Sadhananda Priya",
    "Sadvika Rekha",
    "Sahana",
    "Sahavasini",
    "Sahayukta",
    "Sahuli",
    "Sahyaja",
    "Saikatha Ranjani",
    "Saikatha Srona",
    "Saila Desakshi",
    "Sailapadi",
    "Sailavathi",
    "Saindava Gowla",
    "Saindava Gowri",
    "Saindava Kriya",
    "Saindavi",
    "Sairandhiri",
    "Saivalini",
    "Sajjana Nanda",
    "Saka Prakasini",
    "Saka Tholarava",
    "Sakalakala Vardhani",
    "Sakantha",
    "Sakatahastini",
    "Sakthakala Vardhani",
    "Sakthi",
    "Sakti Tarangini",
    "Sakunthala",
    "Sakunthalavarali",
    "Sala Keeka",
    "Salaga Bhairavi",
    "Salaga Velavali",
    "Salaka Bibhasu",
    "Salakam",
    "Salanganatta",
    "Salavi Bangala",
    "Salavi",
    "Salilapriya",
    "Sallalasa",
    "Sallapam",
    "Sallasini",
    "Salva Mukhari",
    "Salvakam",
    "Sama Barbari",
    "Sama Kannada",
    "Sama Kriya",
    "Sama Kurinji",
    "Sama Mukhari",
    "Sama Narayani",
    "Sama Neelakari",
    "Sama Salavi",
    "Sama Swaravali",
    "Sama Varali",
    "Sama Vasantham",
    "Sama",
    "Samalapini",
    "Saman",
    "Samanojwala",
    "Samantha Deepakam",
    "Samantha Jingla",
    "Samantha Mallaru",
    "Samantha Maruva",
    "Samantha Salavi",
    "Samantha Sikamani",
    "Samantha Velavali",
    "Samantha",
    "Samantham",
    "Samanthini",
    "Samara Ranjani",
    "Samaraga",
    "Sambari Priya",
    "Sambhavi",
    "Sambhu Dhyuthi",
    "Sambramaleelakara",
    "Sambrandaka",
    "Sambu kriya",
    "Sameeranan",
    "Sampradaya Thodi",
    "Sampurna Natakurinji",
    "Samrakshini",
    "Samudra Priya",
    "Samvesini",
    "Sanavi",
    "Sanchalitha",
    "Sandanavali",
    "Sandharsini",
    "Sangamana",
    "Sangraha Priya",
    "Sangrama",
    "Sanjeeva Karani",
    "Sanjh",
    "Sanjivini",
    "Sankara Lalith",
    "Sankara Mohana",
    "Sankara Priya",
    "Sankara Srungarini",
    "Sankara",
    "Sankarabaranam",
    "Sankaranandana Priya",
    "Sankarava",
    "Sankari Mukhari",
    "Sankari",
    "Sannihitha",
    "Santana Manjari (Sarpavathi)",
    "Santanika",
    "Santha Kalyani",
    "Santha Kesari",
    "Santha Murthi",
    "Santhana Deepika",
    "Santhaswarupi",
    "Santva Bhasini",
    "Sapthaswarakirani",
    "Sara Bindhu",
    "Sara Vibhasitham",
    "Sarabha Khanditha",
    "Sarabhadwaja",
    "Sarada Baranam",
    "Sarada Bharani",
    "Sarada Mathi",
    "Saradha Bhairavi",
    "Saradha Priya",
    "Saradha",
    "Saradhyuthi",
    "Saradindhu Mukha",
    "Saradwini",
    "Sarala",
    "Saramathi (Kalidasa Priya)",
    "Saranga Bauli",
    "Saranga Bramari",
    "Saranga Kapi",
    "Saranga lalitha",
    "Saranga Mallaru",
    "Saranga Maruva",
    "Saranga Nata",
    "Saranga Nattai",
    "Saranga Tharangini",
    "Saranga",
    "Sarangada Ranjani",
    "Sarangagaula",
    "Sarangaleela",
    "Sarangamani",
    "Sarangapani",
    "Sarangi",
    "Sarasa Bhashini",
    "Sarasa Chintamani",
    "Sarasa Kalyani",
    "Sarasa Mandini",
    "Sarasa Mangala",
    "Sarasa Nayaki",
    "Sarasa Priya",
    "Sarasa Vahini",
    "Sarasam",
    "Sarasanana",
    "Sarasavani",
    "Sarasiruha Priya",
    "Sarasiruha",
    "Saraswati Manohari",
    "Saraswati Ranjani",
    "Saraswati",
    "Sarathi Gowla",
    "Sarathi",
    "Saravardhini",
    "Saravasri",
    "Saravibhashini",
    "Saravilambi",
    "Sardhalangi",
    "Sardhalanji",
    "Sardhula Manjari",
    "Sarjamani",
    "Sarmila",
    "Sarojam",
    "Sarojini",
    "Sarpanthiri",
    "Sarva Bhauma",
    "Sarva Kunthala",
    "Sarva Manavathi",
    "Sarva Mangala",
    "Sarva Mathi",
    "Sarva Ranjani",
    "Sarva Vahini",
    "Sarvakala Manjari",
    "Sarvangi",
    "Sarvarathi",
    "Sarvari",
    "Sarveswari",
    "Sasa",
    "Sasi Bhaskara",
    "Sasi Dharidri",
    "Sasi Prakasini",
    "Sasi Vadana",
    "Sasipriya",
    "Sasthra Dhini",
    "Sasva",
    "Saswaka",
    "Sathi Resam",
    "Sathvamanjari",
    "Sathvidhi",
    "Sathya Bhushani",
    "Satkavitha",
    "Satputri",
    "Satya Nayaki",
    "Satyavati",
    "Saudhari",
    "Saugandhini",
    "Saura Vahini",
    "Saurashtrakam",
    "Saurashtram",
    "Saveri",
    "Savithri",
    "Savvera",
    "Sayana Ranjani",
    "Sayujya Dharini",
    "Seelangi",
    "Seemanthini",
    "Seena",
    "Seetala Keervani",
    "Seetha Panchamam",
    "Seethakirani",
    "Sekari",
    "Sekhara Chandrika",
    "Selvamani",
    "Selvanayaki",
    "Sena Jayanthi",
    "Sena Ranjani",
    "Sena Rava",
    "Senagrani (Senavathi)",
    "Senamani",
    "Senamanohari",
    "Senapathi",
    "Sendan",
    "Serasena",
    "Sesha Bhooshanam",
    "Sesha Nadham",
    "Sesha Prabatha",
    "Sesha Vahini",
    "Seshanada",
    "Sevadhi",
    "Sevvazhi (Yadukulakamboji)",
    "Seyyal",
    "Shadakshari",
    "Shadananapriya",
    "Shadhvi",
    "Shadpada Dhwani",
    "Shadvidha Swarupini",
    "Shadwadwani",
    "Shaka Mukhi",
    "Shakari",
    "Shalirasa",
    "Shalmali",
    "Shalmika",
    "Shamam",
    "Shanga Dhruma",
    "Shanmatrika",
    "Shanmukhi",
    "Shara Mochini",
    "Shardola rava",
    "Shashanka Kirani",
    "Shashi Manjari",
    "Shashi Vadana",
    "Shatju Kambhoji",
    "Sheelavali",
    "Sheshaadri",
    "Shibika",
    "Shikari",
    "Shobavari",
    "Shobavati",
    "Shoka Varali",
    "Shouri Vilasitha",
    "Shuktija Priya",
    "Shyam Kalyani",
    "Sikambhoji",
    "Sikandi Vrutha",
    "Sikirini",
    "Silamban",
    "Simanthini Priya",
    "Simha Chandana",
    "Simha Dwani",
    "Simha Lalitha",
    "Simha Leela",
    "Simha Madhyamam",
    "Simha Varali",
    "Simha Vikrama",
    "Simhala Bhairavi",
    "Simhala Kapi",
    "Simhala",
    "Simhanadam",
    "Simharava",
    "Simharavam",
    "Simhaswarupi",
    "Simhavahini",
    "Simhela Saveri",
    "Simhela Vasantham",
    "Simhela",
    "Simhelavarali",
    "Simhonnatha",
    "Sindhothama",
    "Sindhu Bhairavi",
    "Sindhu Chintamani",
    "Sindhu Desya",
    "Sindhu Dhanyasi",
    "Sindhu Ganta",
    "Sindhu Gantana",
    "Sindhu Gowri",
    "Sindhu Kriya",
    "Sindhu Mandari",
    "Sindhu Maruva",
    "Sindhu Mukhari",
    "Sindhu Natta",
    "Sindhu Ramakriya",
    "Sindhu Salavi",
    "Sindhu Saveri",
    "Sindhu Surati",
    "Sindhu Tarangini",
    "Sindhu",
    "Sindhukannada",
    "Sindhumalavi",
    "Sindhunattakurinji",
    "Singara Mani",
    "Sinjani",
    "Sinjini",
    "Sirodhi",
    "Sitta Sena",
    "Sittavali",
    "Siva Gandhari",
    "Siva Kambhoji",
    "Siva Murthi",
    "Siva Panthuvarali",
    "Siva Ranjani",
    "Sivachudamani",
    "Sivagangai",
    "Sivai",
    "Sivakampuri",
    "Sivamanohari",
    "Sivanandam",
    "Sivanandi",
    "Sivanayaki",
    "Sivapriya",
    "Sivasakthi",
    "Skanda Manorama",
    "Slokavarali",
    "Smokambari",
    "Sobaswini",
    "Sobhambika",
    "Sochikabaranam",
    "Sohini",
    "Soka Bimba",
    "Soka Varali",
    "Soma Bhairavi",
    "Soma Bhoopalam",
    "Soma Deepakam",
    "Soma Gantanam",
    "Soma Giri",
    "Soma Kriya",
    "Soma Manjari",
    "Soma Prabhavali",
    "Soma Pratapa",
    "Somakirani",
    "Somamukhi",
    "Soman",
    "Somanathan",
    "Somaraga",
    "Somatarangini",
    "Someswara Priya",
    "Somurthika",
    "Sonangari",
    "Sonavati",
    "Soudamani",
    "Soundarya",
    "Soura Sena",
    "Souryavardhini",
    "Sowjanya",
    "Sowkya Dhayini",
    "Sowmya Manohari",
    "Sowrashtram",
    "Sputalapini",
    "Sramahara",
    "Sravana Garbitha",
    "Sravana Mallika",
    "Sravanthi",
    "Sree Santha Bhashini",
    "Sreyo Dharini",
    "Sri Bhanudeepam",
    "Sri Bindumalini",
    "Sri Binnapanchamam",
    "Sri Bramara Uttari",
    "Sri Brindavana Saranga",
    "Sri Chandrika",
    "Sri Deepakam",
    "Sri Dhavalahamsi",
    "Sri Ganavaridhi",
    "Sri Gantanam",
    "Sri Hamsa Bhushani",
    "Sri Hamsa Narayani",
    "Sri Hari",
    "Sri Hindola vasantham",
    "Sri Indhu Bhogi",
    "Sri Jouda Gandhari",
    "Sri Kaikavasi",
    "Sri Kaivalyam",
    "Sri Kaivasi",
    "Sri Kalkada",
    "Sri Kamalaptam",
    "Sri Kamalaveni",
    "Sri Kanada",
    "Sri Kandeesan",
    "Sri Kannan",
    "Sri Kanti",
    "Sri Kari",
    "Sri Karpakambigai",
    "Sri Kedaram",
    "Sri Ketaka Priya",
    "Sri Kirvani",
    "Sri Kunjari",
    "Sri Kuvalaya Baranam",
    "Sri Lalitha",
    "Sri Lochana Priya",
    "Sri Madhava Manohari",
    "Sri Madhukari",
    "Sri Mahabalagiri",
    "Sri Manji",
    "Sri Manjula",
    "Sri Manohari",
    "Sri Manoranjani",
    "Sri Murthi",
    "Sri Nabomargini",
    "Sri Nalinakanthi",
    "Sri Nandana",
    "Sri Narayana Desakshi",
    "Sri Narayani",
    "Sri Natakurinji",
    "Sri Navamani Chandrika",
    "Sri Navarasa Chandrika",
    "Sri Navaratna Bhushani",
    "Sri Omkara Bhoshani",
    "Sri Padmavathi",
    "Sri Ramani",
    "Sri Ranjani",
    "Sri Ratnambari",
    "Sri Saurashtram",
    "Sri Savithri",
    "Sri Supradeepam",
    "Sri Surati",
    "Sri Thakirini",
    "Sri Theevra Vahini",
    "Sri Uzhaimarutham",
    "Sri Vedagiri",
    "Sri Veera Vasantham",
    "Sri Vegavahini",
    "Sri Velavali",
    "Sri",
    "Srikala",
    "Srikanta Vilepani",
    "Srimalavi",
    "Srimangala",
    "Srimani",
    "Srimati",
    "Srinavarasa Bangala",
    "Sringaramani",
    "Sringarini",
    "Sritha Pasvini",
    "Srivivardhini",
    "Sroni",
    "Srothasvini",
    "Srunga Mola",
    "Srungara Lalitha",
    "Srungara Murthi",
    "Srungara Vardhini",
    "Srungarini",
    "Srungi",
    "Sruthi Natta",
    "Sruthi Prakasini",
    "Sruthi Priya",
    "Sruthiranjani",
    "Stauthra Priya",
    "Stavapriya",
    "Sthava Raja",
    "Sthula Varithi",
    "Stuthi Priya",
    "Subha Kari",
    "Subha Mathi",
    "Subha Vahini",
    "Subha Varali",
    "Subhali",
    "Subhangi",
    "Subhashini",
    "Subhasri",
    "Subhavathi",
    "Subhoshini",
    "Subhushani",
    "Subika",
    "Subra Vahini",
    "Subra Varali",
    "Sudalayadi",
    "Sudarangini",
    "Suddha Bairavi",
    "Suddha Bangala",
    "Suddha Bhogi",
    "Suddha Bilawal",
    "Suddha Billari",
    "Suddha Borjari",
    "Suddha Desi",
    "Suddha Dhanyasi",
    "Suddha Gamakakriya",
    "Suddha Gandharva",
    "Suddha Ganta",
    "Suddha Gantanam",
    "Suddha Gantarava",
    "Suddha Ghandari",
    "Suddha Girvani",
    "Suddha Gottamani",
    "Suddha Gowla",
    "Suddha Gowri Priya",
    "Suddha Gurjari",
    "Suddha Hindolam (Varam)",
    "Suddha Jingla",
    "Suddha Jyotishmathi",
    "Suddha Kaivasi",
    "Suddha Kalanidhi",
    "Suddha Kalyan",
    "Suddha Kampitham",
    "Suddha Kannada",
    "Suddha Kosala",
    "Suddha Kriya",
    "Suddha Lalitha",
    "Suddha Madhyamam",
    "Suddha Malahari",
    "Suddha Malavi",
    "Suddha Manjari",
    "Suddha Manohari",
    "Suddha Maruva",
    "Suddha Mohini",
    "Suddha Mukari",
    "Suddha Nattai",
    "Suddha Navaneetham",
    "Suddha Nepala",
    "Suddha Nilambari",
    "Suddha Nirmada",
    "Suddha Panchalika",
    "Suddha Puttari",
    "Suddha Rasali",
    "Suddha Ratnabhanu",
    "Suddha Salavi",
    "Suddha Samantham",
    "Suddha Sanchari",
    "Suddha Saranga",
    "Suddha Satva",
    "Sudda Saveri (Karnataka)",
    "Suddha Seemanthi",
    "Suddha Sena",
    "Suddha Shyamala",
    "Suddha Sikamani",
    "Suddha Simharavam",
    "Suddha Sruthi Ranjani",
    "Suddha Sulini",
    "Suddha Swaravali",
    "Suddha Tarangini",
    "Suddha Thodi",
    "Suddha Uttari",
    "Suddha Varali",
    "Suddha Vasantham",
    "Suddha Velavali",
    "Suddha",
    "Sudha Kalyani",
    "Sudha Kamboji",
    "Sudha Kesari",
    "Sudha Lahari",
    "Sudha Manohari",
    "Sudha Narayani",
    "Sudha Sagaram",
    "Sudha Tarangini",
    "Sudha",
    "Sudhambodhi",
    "Sudharamani",
    "Sudheepaka",
    "Sugandamarutha",
    "Sugathri",
    "Sughandi",
    "Sughoshani",
    "Suguna Bhushani",
    "Sujana Priya",
    "Sujana Ranjani",
    "Sujaskavali",
    "Suka Kari",
    "Suka Latha",
    "Suka Mandara",
    "Suka Neelambari",
    "Suka Pavani",
    "Suka Priya",
    "Suka Ranjani",
    "Suka Saindavam",
    "Suka Swaravali",
    "Sukha Dayini",
    "Sukha Dhwani",
    "Sukhavani",
    "Sukla Karnataka",
    "Sukra Jyothi",
    "Sukra Kantham",
    "Sukra Prabha",
    "Sukra Vardhana",
    "Sukshma Rupi",
    "Sukshma Swarupi",
    "Sukumari",
    "Sula Rekha",
    "Suladharini",
    "Suma Bowri",
    "Suma Tarangini",
    "Sumadhyuthi",
    "Sumana Priya",
    "Sumanesh Ranjani",
    "Sumanisa Priya",
    "Sumukham",
    "Sunadapriya (Sunadanapriya)",
    "Sunadha Vinodhini",
    "Sunadha",
    "Sunadhala",
    "Sundara Bhairavi",
    "Sundara Hemavathi",
    "Sundarasitha Priya",
    "Sundaravana",
    "Suposhini",
    "Supra Bedam",
    "Supra Deepa",
    "Supra Kethana",
    "Suprakasi",
    "Suprakasini",
    "Suprasvini",
    "Suprathapam",
    "Supravahini",
    "Supravarni",
    "Supura",
    "Sura Bairavi",
    "Sura Mani",
    "Sura Nandhini",
    "Sura Varali",
    "Sura Vikrama",
    "Surabhushani",
    "Surabi Priya",
    "Suradhambhudi",
    "Suranati",
    "Surasindhu",
    "Surati Nayaki",
    "Surati",
    "Suratimallaru",
    "Suravarali",
    "Sureswari",
    "Surika",
    "Suru Ranjani",
    "Suru Sena",
    "Survakam",
    "Surya Jyothi",
    "Surya Kauns",
    "Surya Mani",
    "Suryaka Madhyamam",
    "Suryalalith",
    "Susavali",
    "Sushma",
    "Suthakara Priya",
    "Sutradhari",
    "Suvarna Deepakam",
    "Suvarna Deepika",
    "Suvarna Kriya",
    "Suvarna Mukhari",
    "Suvrutha",
    "Svaratna Deepika",
    "Swabhu",
    "Swara Bhushani",
    "Swara Chintamani",
    "Swara Gandhari (Sarva Gandhari)",
    "Swara Kalanidhi",
    "Swara Kesari",
    "Swara Mathi",
    "Swara Ranjani",
    "Swara Sammodhini",
    "Swara Vali",
    "Swara Vardhini",
    "Swara Vedi",
    "Swarabharana",
    "Swarashtra",
    "Swarna Bhodamani",
    "Swarna Choodamani",
    "Swarna Kanthi",
    "Swarna Malli",
    "Swarna Mallika",
    "Swarnambari",
    "Swayambhuswararaga",
    "Swayamvara",
    "Sweeya",
    "Swethambari",
    "Swethambhudi",
    "Swethavarna",
    "Swyrini",
    "Syama Chintamani",
    "Syama Gaula",
    "Syama Kalyan",
    "Syama Neelambari",
    "Syama",
    "Syamala Srutha",
    "Syamala Varni",
    "Syamala Vasantham",
    "Syamala",
    "Syamali",
    "Syamandholana",
    "T",
    "Talamargini",
    "Tapasvini",
    "Tapollasini",
    "Tara Ranjitha",
    "Tatillatika",
    "Teeka",
    "Thaapa Raga",
    "Thakkaragam (Kamboji)",
    "Thakkesi (Kamboji)",
    "Thakrapathi",
    "Thala Ranjani",
    "Thalyam",
    "Thamari",
    "Thamasa Ranjani",
    "Thamasvini",
    "Thamodini",
    "Thamohini",
    "Thamomani",
    "Thamra Kethana",
    "Thamra Ranjani",
    "Thandava Priya",
    "Thandavam",
    "Thandavollasini",
    "Thandholika",
    "Thannavan",
    "Thantrikila",
    "Thanukirthi",
    "Thapa Ranjani",
    "Thapanan",
    "Thapasa Priya",
    "Thara Bharanam",
    "Thara Jyothi",
    "Tharaka Pathi Priya",
    "Tharaka Vasantham",
    "Tharalam",
    "Tharanga Leela",
    "Tharanga",
    "Tharangini",
    "Tharapallaava",
    "Tharatalam",
    "Tharava",
    "Tharavali",
    "Tharinjikam",
    "Tharunipriya",
    "Thashpi Pala",
    "Thatika Panchamam",
    "Thava Mukhari",
    "Thava Sarasiruham",
    "Thavi",
    "Thayala Kamas",
    "Theerva Vardhini",
    "Theevra Vahini",
    "Thejovathi",
    "Thekkali",
    "Thikaruni",
    "Thilakaprakasini",
    "Thillai Nayaki",
    "Thillang",
    "Thiru Kandan",
    "Thiru Madandai",
    "Thiru Murugan",
    "Thiru navudayar",
    "Thirumurai Vadivam",
    "Thitti",
    "Thittipa Dhwani",
    "Thivrika Vasantham",
    "Thodi",
    "Thomara Dharini",
    "Thomrapani",
    "Thoomala",
    "Thoya Dhara Varshini",
    "Thoya Vegavahini",
    "Thrana Sobhi",
    "Thriyama",
    "Thriyambini",
    "Thulikal Vichitra",
    "Thulikiya",
    "Thunga Naga",
    "Thusaravarni",
    "Thyagan",
    "Tiraskarani",
    "Tirumurthi",
    "Tirumurthi Priya",
    "Tirumurthi",
    "Tridasi Ranjani",
    "Trilochana Priya",
    "Trinetra Priya",
    "Tripataka",
    "Tripureeswari",
    "Trisuli",
    "Triveni",
    "Trivikrini",
    "Triyambakapriya",
    "Tuniradharini",
    "Turanga Leela",
    "U",
    "Udaya Bhairavi",
    "Udaya Chandrika",
    "Udaya Ravi",
    "Udaya Ravichandrika",
    "Ugran",
    "Ukavani",
    "Umabaranam",
    "Unnamalai",
    "Upendra Mathi",
    "Upendra Vajra",
    "Upendran",
    "Uragamani",
    "Urmika",
    "Urmila",
    "Usanan",
    "Ushavali",
    "Uttari (Puttari)",
    "Utthangamana",
    "Uzhai Marutham",
    "V",
    "Vaadivasantha - Bairav",
    "Vaasa Varithi",
    "Vaatha Chandrika",
    "Vadhithya Vinodhini",
    "Vagheeswari",
    "Vaghva Mukhi",
    "Vagra Nandana",
    "Vagvaditya",
    "Vagvilalitha",
    "Vagvilasitha",
    "Vagvimathi",
    "Vahini",
    "Vahulasri",
    "Vaidharba",
    "Vaijayanthi",
    "Vaisakham",
    "Vaishnavi",
    "Vaisukri",
    "Vajra Gandhi",
    "Vajrachudamani",
    "Vajrahasitha",
    "Vakkal",
    "Valaji",
    "Vali Thodi",
    "Vallabhi",
    "Vallavan",
    "Vallika",
    "Vallikakila",
    "Vama Sukirini",
    "Vamalochana",
    "Vamsavathi",
    "Vamsikam",
    "Vana Dayaki",
    "Vana Vasundara",
    "Vanaja Mukhi",
    "Vanajambari",
    "Vanajarini",
    "Vanali",
    "Vanamali",
    "Vandhana Dharini",
    "Vandhya Mukhi",
    "Vani Panchamam",
    "Vani Sri",
    "Vanthika",
    "Varadhan",
    "Varadhari",
    "Varali Thilakam",
    "Varali",
    "Varam",
    "Varan",
    "Varata",
    "Varati",
    "Varavarnini",
    "Vardhini",
    "Varini",
    "Varitha Ranjani",
    "Varithae",
    "Varna Deepika",
    "Varna Dhwaja",
    "Varna Kadari",
    "Varna Karina",
    "Varnakurinji",
    "Varnarupini",
    "Varudha",
    "Varuna Dhwaja",
    "Varuna Sindhu",
    "Varunanidhi",
    "Vasantha Bhairavi",
    "Vasantha Bhoopalam",
    "Vasantha Ganthi",
    "Vasantha Goshi",
    "Vasantha Gowla",
    "Vasantha Kannada",
    "Vasantha Keervani",
    "Vasantha Leela",
    "Vasantha Leelavati",
    "Vasantha Manohari",
    "Vasantha Maruva",
    "Vasantha Mukhari",
    "Vasantha Narayani",
    "Vasantha Priva",
    "Vasantha Sri",
    "Vasantha Srimani",
    "Vasantha Varali",
    "Vasantha",
    "Vasanthaka",
    "Vasanthi",
    "Vasava Lalitha",
    "Vasi Manjari",
    "Vasodhari",
    "Vasugarbha",
    "Vasukari",
    "Vasumathi",
    "Vatsa",
    "Vatsam",
    "Vattambari",
    "Veda Dayi",
    "Veda Swarupi",
    "Vedaghosha Priya",
    "Vedagiri",
    "Vedambari",
    "Vedanda Gamana",
    "Vedanjani",
    "Vedavalli",
    "Vedika",
    "Veena Dhari",
    "Veena Vadhini",
    "Veer Vasantham",
    "Veera Gantaravam",
    "Veera Leela",
    "Veera Megham",
    "Veera Nayaki",
    "Veera Prathapam",
    "Veera Rani",
    "Veera Sankarabaranam",
    "Veera Vahini",
    "Veeradhi Vasantham",
    "Veeragan",
    "Veeralan",
    "Veeran",
    "Veeranatha",
    "Veerasankashini",
    "Veeravarali",
    "Veeravasantham",
    "Veeravikrama",
    "Veetika",
    "Vegamalini",
    "Vegavahini",
    "Velavali",
    "Venkatachalan",
    "Venkataadri",
    "Venukarama",
    "Vibhavari",
    "Vichithrambari",
    "Vidamba (Vidambamathi)",
    "Vidasandhohini",
    "Vidasokan",
    "Vidatha",
    "Vidhana Sanki",
    "Vidhya Mali",
    "Vigna Ranjitha",
    "Vihangika",
    "Vijaya Beedu",
    "Vijaya Bharani",
    "Vijaya Bhushavali",
    "Vijaya Deepika",
    "Vijaya Gothrari",
    "Vijaya Kokila",
    "Vijaya Kosala",
    "Vijaya Nagari",
    "Vijaya Pradha",
    "Vijaya Ratnakari",
    "Vijaya Samantham",
    "Vijaya Saranga",
    "Vijaya Saraswati",
    "Vijaya Sri",
    "Vijaya Srikanti",
    "Vijaya Vardhini",
    "Vijaya Vasantham",
    "Vijayanarayani",
    "Vijayollasini",
    "Viji Kalitha",
    "Vijrumbini",
    "Vikasithananda",
    "Vikavati (Vivadiva)",
    "Vikrama Varali",
    "Vikrama",
    "Vilakshana",
    "Vilambini",
    "Vilamburi",
    "Vilas Vathi",
    "Vilasini",
    "Villagakoli",
    "Villi",
    "Vimala Mohan",
    "Vimali",
    "Vimanasathi",
    "Vinaya Mrughi",
    "Vinodhini",
    "Vipra Dhanyasi",
    "Vipra Mandara",
    "Vipra Mathi",
    "Vipula",
    "Vipuni",
    "Vira Janthaka",
    "Virati",
    "Virujina Hirani",
    "Visangini",
    "Visaveer",
    "Visharadha",
    "Vishna Baranam",
    "Vishnu Priya",
    "Vishnupathi",
    "Visupathi",
    "Viswadhatrri",
    "Viswanarayani",
    "Vitapi",
    "Vivardhini",
    "Vivo Ranjani",
    "Vratha Baranam",
    "Vrishabavahini",
    "Vrishamani",
    "Vruddha Sumuki",
    "Vrushabaadri",
    "Vuruga Manjari",
    "Vyagra Manjari",
    "Vyazha Kurinji",
    "W",
    "Wariar",
    "Y",
    "Yadhukula Kamboji",
    "Yaga Jyothi",
    "Yagna Priya",
    "Yakshapriya",
    "Yami",
    "Yamuna Kalyani",
    "Yasomani",
    "Yathi karshan",
    "Yauchana",
    "Yauvani",
    "Yava Priya",
    "Yazh Vallone",
    "Yazhisai Arasu",
    "Yoga Bhairavi",
    "Yoga Bhodini",
    "Yoga Gandhari",
    "Yoga Mathi",
    "Yoga Sarabhi",
    "Yogagiri",
    "Yogaleela",
    "Yoganandi",
    "Yogavathi",
    "Yogini",
    "Yuddha Pravarthini",
    "Yuddhevika",
    "Yuvaratna",
  ],
  tala: ["Adi", "Ata", "Dhruva", "Eka", "Jhampa", "Matya", "Rupaka", "Triputa"],
  type: ["Divotional", "Folk", "Movie", "Yakshagana"],
  default: [],
};

export enum DataItem {
  Raga = "raga",
  Tala = "tala",
  Type = "type",
  Default = "default",
}

export interface FilterSelection {
  selectionType: DataItem;
  selectItem: (item: string, id: string) => void;
}

const FilterSelection = (props: FilterSelection) => {
  const { selectionType, selectItem } = props;

  const dispatch = useDispatch();
  const [itemsList, setItemsList] = useState<string[]>([]);

  useEffect(() => {
    setItemsList(dataList[selectionType]);
  }, []);

  const handleFilter = (e: ChangeEvent) => {
    const searchKey = (e.target as HTMLInputElement).value;
    const data = dataList[selectionType];
    setItemsList(() => {
      return data.filter((item: string) =>
        item.toLowerCase().includes(searchKey.toLowerCase())
      );
    });
  };

  const handleItemSelection = (item: string) => {
    selectItem(item, selectionType);
    dispatch(hideSearchFilter());
  };

  return (
    <div className="filter-selection">
      <div className="search-bar-container">
        <div className="search-bar">
          <input
            type="text"
            placeholder="Search raga"
            onChange={(e) => handleFilter(e as ChangeEvent)}
          />
          <div
            className="filter-icon"
            onClick={() => {
              dispatch(hideSearchFilter());
            }}
          >
            <FontAwesomeIcon icon={faTimes} />
          </div>
        </div>
        <div className="list-contaner">
          {itemsList.map((item: string, index) => (
            <div
              className="list"
              key={index}
              onClick={() => handleItemSelection(item)}
            >
              <div className="list-text">{item}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default FilterSelection;
